run:
  timeout: 5m

  issues-exit-code: 1

output:
  format: colored-line-number

  print-issued-lines: true

  print-linter-name: true

  uniq-by-line: true

  path-prefix: ""

  sort-results: false

linters-settings:
  cyclop:
    max-complexity: 30

  dogsled:
    max-blank-identifiers: 2

  dupl:
    threshold: 100

  errcheck:
    check-type-assertions: true

    check-blank: true

  godot:
    scope: declarations
    capital: false

  errorlint:
    errorf: true
    asserts: true
    comparison: true

  godox:
    keywords: # default keywords are TODO, BUG, and FIXME, these can be overwritten by this setting
      - NOTE
      - OPTIMIZE # marks code that should be optimized before merging
      - HACK # marks hack-arounds that should be removed before merging

  funlen:
    lines: 60
    statements: 40

  gocognit:
    min-complexity: 20

  linters-settings:
  nestif:
    min-complexity: 4

linters:
  disable-all: true
  enable:
    - godox
    - dogsled
