name: codecov
on:
  pull_request:
    branches: [ main, feature*, prerelease* ]
  push:
    branches:
      - main
jobs:
  codecov:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-go@v4
      with:
        go-version: '1.20'
    - uses: actions/checkout@v3

    - name: codecoverage
      run: |
        go test -mod=mod -covermode=count  -p 1  -coverpkg=../internal/...,../pkg/... ./... -coverprofile=cover_temp.out